- name: Create a VLAN
  hosts: localhost
  vars:
    ucs_hostname: "{{ user_ucs_hostname }}"
    ucs_username: "{{ user_ucs_username }}"
    ucs_password: "{{ user_ucs_password }}"
    vlan_name: "kolibrie-orc-{{ kolibrie_vlan_id }}"
    vlan_id: "{{ kolibrie_vlan_id }}"

  tasks:
    - name: "Create a VLAN ({{ vlan_id }})"
      ucs_vlans:
        hostname: "{{ ucs_hostname }}"
        username: "{{ ucs_username }}"
        password: "{{ ucs_password }}"
        name: "{{ vlan_name }}"
        id: "{{ vlan_id }}"
        native: 'no'
        state: present
